# Generated by Django 4.1 on 2022-08-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
