# Generated by Django 4.1 on 2022-08-12 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0004_delete_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_delet', models.BooleanField(default=False, verbose_name='Друзья')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL, verbose_name='Тот кто хочет дружить')),
                ('profil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='user_profile.userprofile', verbose_name='Тот с кем хочет дружить')),
            ],
        ),
    ]
